name: self_service
description: SelfService application to generate an application
dependencies:
    angular: any
    browser: any
    json_object: any
    web_components: any
    #paper_elements: ">=0.5.0 <0.6.0"
    #core_elements: any
    highcharts4dart: any
    jquery_for_pub: any
    bootstrap_for_pub: '>=3.3.0+1 <4.0.0'
    dart_jwt: ">=0.1.2 <0.2.0"
    spectingular_dart:
        git:
          url: https://github.com/hvdb/Spectingular.Dart.git
          ref: develop
dependency_overrides:
    angular: '0.14.0'
    intl: '0.11.9'
    web_components: '0.9.0'
    html5lib: '0.11.0+1'
    args: 0.11.0
    code_transformers: 0.2.3
dev_dependencies:
    unittest: any
    protractor: '0.0.5'
    dartmocks: ">= 0.5.0"
    guinness: ">= 0.1.3"
transformers:
- angular
- $dart2js:
    minify: true
- bootstrap_for_pub:
     url: //maxcdn.bootstrapcdn.com/bootstrap/{{version}}
     version: 3.2.0
