name: self_service
description: SelfService application to generate an application
dependencies:
    angular: any
    browser: any
    json_object: any
    web_components: any
dev_dependencies:
    unittest: any
    protractor: '0.0.5'
    dartmocks: ">= 0.5.0"
    guinness: ">= 0.1.3"
transformers:
- angular
- $dart2js:
    minify: true
